name: Generate ASCII
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install cowsay Program
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y
      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
      - name: Read File
        run: cat dragon.txt
      - name: Checkout Repo Files
        run: ls -ltra
      - name: Run cowsay
        run: cowsay -f dragon "run for cover, I am a dragon....RAWR" >> dragon.txt